import image from '../images/logo.png';
import { useEffect,useState } from 'react'
import axios from 'axios'
import { Spinner,Card} from 'react-bootstrap'

const Home = (props) => {

    const[data,setData] = useState([])
    const[loading,setLoading] = useState(true)

    const fetchLaunchFromAPI = () => {
        try{
          axios.get(`https://api.nytimes.com/svc/books/v3/lists/full-overview.json?api-key=uak3NkFGVEYRiY8vMZe3QI09uAQBYefi`)
          .then(response => {
              if (response !== undefined){
                  console.log(`mission details : ${JSON.stringify(response.data)}`)
                  setData(response.data)
                  props.setBooks(response.data)
                  setLoading(false)
              }else{
                  console.log("No data received in response");
                  setLoading(false)
              }
          })
          .catch(err => {
              console.log(`Cannot connect to API due to error : ${err}`);
              setLoading(false)
          }) 
          }
          catch(error){
              console.log(`Error while fetching data from API: ${error}`);
              setLoading(false)
          }
    }

    useEffect(() => {fetchLaunchFromAPI()},[])
        
    return (
        <div className='home'>
            <h1>Welcome to Brain Feed!</h1>
            <img className='logo' src={image} alt="Brain Feed" height='100px' width='100px'/> {/*The image is generated by AI*/}
            <p id="intro">Where knowledge meets nourishment. At Brain Feed, we're not just a bookstore; we're the source of sustenance for your intellect. With a diverse selection of books spanning various genres, from insightful non-fiction to captivating fiction. We offer the perfect ingredients to fill your empty mind and enrich your brain. Our mission is to provide the nutrients your intellect craves, helping you grow and flourish through the power of books. Come, feed your brain and discover a world of boundless possibilities at Brain Feed.</p>
            <br/>
            <h1>New Releases</h1>
            {loading ? (
                <Spinner animation = "border" role = "status">
                    <span className='visually-hidden'>Loading....</span>
                </Spinner>
            ) : (
            <div>
            {data.results.lists ? (
                data.results.lists[0].books.map(book => (
                        <Card style={{width: '18%', margin: '1%', height: '280px', float: 'left'}}>
                        <Card.Body key={book.title}>
                            <Card.Img style = {{height:'120px' ,width:'80px'}} variant = "top" src = {book.book_image}/>
                            <Card.Title style={{paddingTop:15}}><b>{book.title}</b></Card.Title>
                            <Card.Text><b>Author:</b> {book.author}</Card.Text>                
                        </Card.Body>
                        </Card>
                    ))
            ) : (
                <h2>No books available</h2>
            )}
            </div>
        )
      }
            </div>
        );
    }
    
    export default Home;